In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report

df = pd.DataFrame.from_csv('HR.csv', index_col=None)
df = df.rename(columns={'satisfaction_level': 'satisfaction', 
                        'last_evaluation': 'evaluation',
                        'number_project': 'projectCount',
                        'average_montly_hours': 'averageMonthlyHours',
                        'time_spend_company': 'yearsAtCompany',
                        'Work_accident': 'workAccident',
                        'promotion_last_5years': 'promotion',
                        'sales' : 'department',
                        'left' : 'turnover'
                        })
df["department"] = df["department"].astype('category').cat.codes
df["salary"] = df["salary"].astype('category').cat.codes

front = df['turnover']
df.drop(labels=['turnover'], axis=1,inplace = True)
df.insert(0, 'turnover', front)

# Create train and test splits
target_name = 'turnover'
X = df.drop('turnover', axis=1)
#robust_scaler = RobustScaler()
#X = robust_scaler.fit_transform(X)
y=df[target_name]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.15, random_state=123, stratify=y)
rf = RandomForestClassifier(
    n_estimators=1000, 
    max_depth=None, 
    min_samples_split=10, 
    class_weight="balanced"
    #min_weight_fraction_leaf=0.02 
    )
rf.fit(X_train, y_train)
print ("\n\n ---Random Forest Model---")
rf_roc_auc = roc_auc_score(y_test, rf.predict(X_test))
print ("Random Forest AUC = %2.2f" % rf_roc_auc)
print(classification_report(y_test, rf.predict(X_test)))

 ---Random Forest Model---
Random Forest AUC = 0.98
             precision    recall  f1-score   support

          0       0.99      1.00      0.99      1714
          1       0.99      0.96      0.98       536

avg / total       0.99      0.99      0.99      2250

In [4]:
from sklearn import tree

dtree = tree.DecisionTreeClassifier(
    #max_depth=3,
    class_weight="balanced",
    min_weight_fraction_leaf=0.01
    )
dtree = dtree.fit(X_train,y_train)
print ("\n\n ---Decision Tree Model---")
dt_roc_auc = roc_auc_score(y_test, dtree.predict(X_test))
print ("Decision Tree AUC = %2.2f" % dt_roc_auc)
print(classification_report(y_test, dtree.predict(X_test)))

 ---Decision Tree Model---
Decision Tree AUC = 0.94
             precision    recall  f1-score   support

          0       0.97      0.97      0.97      1714
          1       0.92      0.91      0.92       536

avg / total       0.96      0.96      0.96      2250

In [5]:
from sklearn.externals.six import StringIO  
import pydotplus
dot_data = StringIO() 
tree.export_graphviz(dtree, out_file=dot_data) 
graph = pydotplus.graph_from_dot_data(dot_data.getvalue()) 
graph

True

In [13]:
import graphviz
labels = list(X.columns)
class_name = ['True','False']
dot_data = tree.export_graphviz(dtree, out_file=None, 
                         feature_names=labels,  
                         class_names=class_name,  
                         filled=True, rounded=True,  
                         special_characters=True)  
graph = graphviz.Source(dot_data)  
graph.render("123.jpg")

'123.jpg.pdf'

In [10]:
dir(graph.save)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__func__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [2]:
df

,turnover,satisfaction,evaluation,projectCount,averageMonthlyHours,yearsAtCompany,workAccident,promotion,department,salary
0,1,0.38,0.53,2,157,3,0,0,7,1
1,1,0.80,0.86,5,262,6,0,0,7,2
2,1,0.11,0.88,7,272,4,0,0,7,2
3,1,0.72,0.87,5,223,5,0,0,7,1
4,1,0.37,0.52,2,159,3,0,0,7,1
5,1,0.41,0.50,2,153,3,0,0,7,1
6,1,0.10,0.77,6,247,4,0,0,7,1
7,1,0.92,0.85,5,259,5,0,0,7,1
8,1,0.89,1.00,5,224,5,0,0,7,1
9,1,0.42,0.53,2,142,3,0,0,7,1
10,1,0.45,0.54,2,135,3,0,0,7,1
11,1,0.11,0.81,6,305,4,0,0,7,1
12,1,0.84,0.92,4,234,5,0,0,7,1
13,1,0.41,0.55,2,148,3,0,0,7,1
14,1,0.36,0.56,2,137,3,0,0,7,1
15,1,0.38,0.54,2,143,3,0,0,7,1
16,1,0.45,0.47,2,160,3,0,0,7,1
17,1,0.78,0.99,4,255,6,0,0,7,1
18,1,0.45,0.51,2,160,3,1,1,7,1
19,1,0.76,0.89,5,262,5,0,0,7,1
20,1,0.11,0.83,6,282,4,0,0,7,1
21,1,0.38,0.55,2,147,3,0,0,7,1
22,1,0.09,0.95,6,304,4,0,0,7,1
23,1,0.46,0.57,2,139,3,0,0,7,1
24,1,0.40,0.53,2,158,3,0,0,7,1
25,1,0.89,0.92,5,242,5,0,0,7,1
26,1,0.82,0.87,4,239,5,0,0,7,1
27,1,0.40,0.49,2,135,3,0,0,7,1
28,1,0.41,0.46,2,128,3,0,0,2,1
29,1,0.38,0.50,2,132,3,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...
14969,1,0.43,0.46,2,157,3,0,0,7,2
14970,1,0.78,0.93,4,225,5,0,0,7,2
14971,1,0.39,0.45,2,140,3,0,0,7,2
14972,1,0.11,0.97,6,310,4,0,0,2,2
14973,1,0.36,0.52,2,143,3,0,0,2,2
14974,1,0.36,0.54,2,153,3,0,0,2,2
14975,1,0.10,0.79,7,310,4,0,0,3,2
14976,1,0.40,0.47,2,136,3,0,0,3,2
14977,1,0.81,0.85,4,251,6,0,0,3,2
14978,1,0.40,0.47,2,144,3,0,0,3,2
14979,1,0.09,0.93,6,296,4,0,0,9,2
14980,1,0.76,0.89,5,238,5,0,0,9,0
14981,1,0.73,0.93,5,162,4,0,0,9,1
14982,1,0.38,0.49,2,137,3,0,0,9,2
14983,1,0.72,0.84,5,257,5,0,0,9,2
14984,1,0.40,0.56,2,148,3,0,0,9,2
14985,1,0.91,0.99,5,254,5,0,0,9,2
14986,1,0.85,0.85,4,247,6,0,0,9,1
14987,1,0.90,0.70,5,206,4,0,0,9,1
14988,1,0.46,0.55,2,145,3,0,0,9,1
14989,1,0.43,0.57,2,159,3,1,0,9,1
14990,1,0.89,0.88,5,228,5,1,0,8,1
14991,1,0.09,0.81,6,257,4,0,0,8,1
14992,1,0.40,0.48,2,155,3,0,0,8,1
14993,1,0.76,0.83,6,293,6,0,0,8,1
14994,1,0.40,0.57,2,151,3,0,0,8,1
14995,1,0.37,0.48,2,160,3,0,0,8,1
14996,1,0.37,0.53,2,143,3,0,0,8,1
14997,1,0.11,0.96,6,280,4,0,0,8,1
14998,1,0.37,0.52,2,158,3,0,0,8,1